package models.pojo;
// Generated May 30, 2016 4:44:37 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private Movie movie;
	private User user;
	private String comment;
	private Date commentTime;

	public Comment() {
	}

	public Comment(Movie movie, User user) {
		this.movie = movie;
		this.user = user;
	}

	public Comment(Movie movie, User user, String comment, Date commentTime) {
		this.movie = movie;
		this.user = user;
		this.comment = comment;
		this.commentTime = commentTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

}
