package models.pojo;
// Generated May 30, 2016 4:44:37 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Director generated by hbm2java
 */
@SuppressWarnings("serial")
public class Director implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date birthday;
	private String nationality;
	@SuppressWarnings("rawtypes")
	private Set movies = new HashSet(0);

	public Director() {
	}

	public Director(String name) {
		this.name = name;
	}

	@SuppressWarnings("rawtypes")
	public Director(String name, Date birthday, String nationality, Set movies) {
		this.name = name;
		this.birthday = birthday;
		this.nationality = nationality;
		this.movies = movies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@SuppressWarnings("rawtypes")
	public Set getMovies() {
		return this.movies;
	}

	@SuppressWarnings("rawtypes")
	public void setMovies(Set movies) {
		this.movies = movies;
	}

}
