package models.pojo;
// Generated May 30, 2016 4:44:37 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
public class User implements java.io.Serializable {
	
	private Integer id;
	private String username;
	private String password;
	private String displayName;
	private Boolean isAdmin;
	private String email;
	private String phone;
	@SuppressWarnings("rawtypes")
	private Set comments = new HashSet(0);

	public User() {
	}

	@SuppressWarnings("rawtypes")
	public User(String username, String password, String displayName, Boolean isAdmin, String email, String phone,
			Set comments) {
		this.username = username;
		this.password = password;
		this.displayName = displayName;
		this.isAdmin = isAdmin;
		this.email = email;
		this.phone = phone;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Boolean getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@SuppressWarnings("rawtypes")
	public Set getComments() {
		return this.comments;
	}

	@SuppressWarnings("rawtypes")
	public void setComments(Set comments) {
		this.comments = comments;
	}

}
